### ISSUE TITLE
BLOCK

### ISSUE THREAD

**Issue by qq617564112** [ACFUN-FOSS/acfunlive-backend#1]
[TellOrzogcWhatHappened.zip](https://github.com/ACFUN-FOSS/acfunlive-backend/files/8192881/TellOrzogcWhatHappened.zip)
![I)N0RNLI5@OO{W}C8}ZX$TF](https://user-images.githubusercontent.com/30554189/156929628-4ee4fb04-42dd-4a53-b086-2c6360e1518a.png)
![Y F {29}2P5N6P%A} 0I8H1](https://user-images.githubusercontent.com/30554189/156929631-a6716a13-fb78-428e-b335-eb0b43d7a4fa.png)

**Comment by orzogc** [comment]
这是被A站block了，现在A站的直播API不能短时间内请求过多，不然会短暂屏蔽IP

**Comment by qq617564112** [comment]
其它接口不会



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 13:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
这是被A站block了，现在A站的API不能短时间内请求过多，不然会短暂屏蔽IP

**Comment by qq617564112** [comment]
频繁请求的又不是这个接口

**Comment by orzogc** [comment]
不是单一接口，是所有`live.acfun.cn`的接口在短时间内合计请求次数过多就会被block

**Comment by qq617564112** [comment]
所有接口请求过多 只有100被block？



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 14:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
不是单一接口，是所有live.acfun.cn的接口在短时间内合计请求次数过多就会被block

**Comment by qq617564112** [comment]
官方网页弹幕🐔为什么还能用



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 14:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
不是单一接口，是所有live.acfun.cn的接口在短时间内合计请求次数过多就会被block

**Comment by qq617564112** [comment]
个别人出现问题 别人没问题？



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 14:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
不是单一接口，是所有live.acfun.cn的接口在短时间内合计请求次数过多就会被block

**Comment by orzogc** [comment]
首先，只会block几分钟，被block了的期间肯定打不开A站的网页直播间，官方弹幕姬能用可能是那时候block被解除了
其次，出现这个问题的有可能是有浏览器插件/脚本/别的A站相关应用在不断请求直播API，再加上工具箱就被block了

**Comment by qq617564112** [comment]
有主播连着2天用不了了 不止几分钟



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 15:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
首先，只会block几分钟，被block了的期间肯定打不开A站的网页直播间，官方弹幕姬能用可能是那时候block被解除了
 其次，出现这个问题的有可能是有浏览器插件/脚本/别的A站相关应用在不断请求直播API，再加上工具箱就被block了

**Comment by qq617564112** [comment]
被block的同时我让他打开的官方弹幕🐔



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 15:21 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
首先，只会block几分钟，被block了的期间肯定打不开A站的网页直播间，官方弹幕姬能用可能是那时候block被解除了
 其次，出现这个问题的有可能是有浏览器插件/脚本/别的A站相关应用在不断请求直播API，再加上工具箱就被block了

**Comment by orzogc** [comment]
其实官方弹幕姬除了其网页本身，根本不用`live.acfun.cn`的接口

**Comment by orzogc** [comment]
你说说出问题的工具箱是哪个版本的？

**Comment by qq617564112** [comment]
从158到1613都有



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 15:26 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
你说说出问题的工具箱是哪个版本的？

**Comment by orzogc** [comment]
仔细看一下，好像不只是`live.acfun.cn`相关接口的限流，快手服务器那边也会限流

现在的解决办法有两种：
- 向A站反馈，要求放松限流阙值，毕竟现在阿彩也在用工具箱
- 工具箱减少请求频率，尤其是周期性的请求

至于哪些请求会被block，还需时间测试和整理

**Comment by qq617564112** [comment]
你去问🐒要sdk



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 15:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
仔细看一下，好像不只是live.acfun.cn相关接口的限流，快手服务器那边也会限流
 
现在的解决办法有两种：
  
向A站反馈，要求放松限流阙值，毕竟现在阿彩也在用工具箱 

工具箱减少请求频率，尤其是周期性的请求 
 
至于哪些请求会被block，还需时间测试和整理

**Comment by orzogc** [comment]
你去，这是工具箱的问题，现在工具箱不归我管

**Comment by orzogc** [comment]
另外换成最新的后端试试

**Comment by qq617564112** [comment]
早就merge了



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 20:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
另外换成最新的后端试试

**Comment by orzogc** [comment]
出问题的用户用的是最新的后端吗？

**Comment by qq617564112** [comment]
新老都有



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 20:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




 
出问题的用户用的是最新的后端吗？

**Comment by orzogc** [comment]
那么出问题的用户是否启用了特别关心功能？这个功能会不断请求110？

**Comment by qq617564112** [comment]
![image](https://user-images.githubusercontent.com/30554189/157049043-e0a4506e-3c35-4474-95f1-a82f907e139f.png)

**Comment by qq617564112** [comment]
![image](https://user-images.githubusercontent.com/30554189/157049123-3426a1e5-a2d1-4b74-8ca2-87371f924d02.png)

**Comment by orzogc** [comment]
> ![image](https://user-images.githubusercontent.com/30554189/157049123-3426a1e5-a2d1-4b74-8ca2-87371f924d02.png)

这个用了浏览器那个acfun助手？可能就是问题原因之一

**Comment by qq617564112** [comment]
---Original---
From: ***@***.***&gt;
Date: Mon, Mar 7, 2022 23:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ACFUN-FOSS/acfunlive-backend] BLOCK (Issue #1)




  

  
这个用了浏览器那个acfun助手？可能就是问题原因之一

**Comment by orzogc** [comment]
你这email有问题，没有具体回信

**Comment by qq617564112** [comment]
我单独在云服务器上部署一个请求弹幕的服务端 一样被block

**Comment by orzogc** [comment]
那你去问猴子究竟是什么问题

**Comment by qq617564112** [comment]
让主播把浏览器插件都去掉 还是会被block

**Comment by orzogc** [comment]
可能是A站识别到爬虫了

**Comment by qq617564112** [comment]
你把接口请求逻辑整理一下写成文字  我让人找猴子

**Comment by orzogc** [comment]
> 你把接口请求逻辑整理一下写成文字 我让人找猴子

https://github.com/wpscott/AcFunDanmaku/blob/master/AcFunDanmu/README.md

**Comment by orzogc** [comment]
> 让主播把浏览器插件都去掉 还是会被block

还有一种解决方法就是重新拨号换IP地址

**Comment by lost4git** [comment]
需要修改 deviceId

**Comment by lost22git** [comment]
如果是对于 `startPlay`  api 或许可以通过 `https://www.acfun.cn/login/?returnUrl=https%3A%2F%2Fwww.acfun.cn%2F` 获取新的 `did`
