### ISSUE TITLE
为什么前一秒还有弹幕过来 后一秒就timeout了

### ISSUE THREAD

**Issue by qq617564112** [ACFUN-FOSS/acfunlive-backend#2]
![image](https://user-images.githubusercontent.com/30554189/158068528-35271100-b5e7-4f8b-bac7-24a53d57579e.png)

**Comment by qq617564112** [comment]
[TellOrzogcWhatHappened.zip](https://github.com/ACFUN-FOSS/acfunlive-backend/files/8240074/TellOrzogcWhatHappened.zip)

**Comment by orzogc** [comment]
这是读超时，说明客户端超过10秒没有发送任何消息（包括心跳）过来
