### ISSUE TITLE
获取直播信息失败

### ISSUE THREAD

**Issue by qq617564112** [ACFUN-FOSS/acfunlive-backend#3]
![AVFPG$OOZC2(~Y5SORWE~4Y](https://user-images.githubusercontent.com/30554189/174481628-8ad0d940-c9fa-4228-9b83-7fda29c2cdca.png)

**Comment by orzogc** [comment]
这是个例还是全部都这样？

**Comment by qq617564112** [comment]
今天突然大范围反应




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ACFUN-FOSS/acfunlive-backend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月19日(星期天) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ACFUN-FOSS/acfunlive-backend] 获取直播信息失败 (Issue #3)





 
这是个例还是全部都这样？

**Comment by orzogc** [comment]
我这里没问题，建议出现这问题的主播重新拨号换IP地址试试

**Comment by orzogc** [comment]
如果还是这样，那就不要用109请求

**Comment by qq617564112** [comment]
![image](https://user-images.githubusercontent.com/30554189/174488735-77404ff0-cd34-42ff-9675-702ef88c40ca.png)
需要这些

**Comment by orzogc** [comment]
用115和903代替
