### ISSUE TITLE
更新到最新api

### ISSUE THREAD

**Issue by qq617564112** [ACFUN-FOSS/acfunlive-backend#4]
![@WEW5$CFN`K1F~LS5GEO5D8](https://user-images.githubusercontent.com/30554189/208027404-2710ba21-ba6e-4516-b85c-a981a49ae3d4.png)
越来越不稳定
type 115

**Comment by qq617564112** [comment]
出现几次提示以后弹幕鸡断连

**Comment by qq617564112** [comment]
[TellOrzogcWhatHappened.zip](https://github.com/ACFUN-FOSS/acfunlive-backend/files/10242871/TellOrzogcWhatHappened.zip)

**Comment by orzogc** [comment]
哪里有什么最新API？

**Comment by qq617564112** [comment]
> 哪里有什么最新API？

弹幕库没更新？

**Comment by orzogc** [comment]
> > 哪里有什么最新API？
> 
> 弹幕库没更新？

没，就上游更新了基于TCP的弹幕连接

**Comment by qq617564112** [comment]
> > > 哪里有什么最新API？
> > 
> > 
> > 弹幕库没更新？
> 
> 没，就上游更新了基于TCP的弹幕连接

电脑端也开始断连了

**Comment by orzogc** [comment]
可以用903代替115

**Comment by qq617564112** [comment]
开播后才有返回什么意思

**Comment by orzogc** [comment]
现在不用109了？

**Comment by qq617564112** [comment]
![image](https://user-images.githubusercontent.com/30554189/208059629-803a29d5-e31c-4d06-b156-615d5c56d900.png)

**Comment by orzogc** [comment]
应该是接口被爬太多崩了或者被限制了吧，你应该去找猴子解决

**Comment by orzogc** [comment]
@qq617564112 试试最新的后端 <https://github.com/ACFUN-FOSS/acfunlive-toolbox-client/pull/86>

**Comment by qq617564112** [comment]
> 

可执行文件呢

**Comment by orzogc** [comment]
> > 
> 
> 可执行文件呢

你合并PR啊 https://github.com/ACFUN-FOSS/acfunlive-toolbox-client/pull/86
